# Generated by Django 4.2 on 2024-03-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TOKEN'),
        ),
    ]
